### ISSUE TITLE
Rename gem

### ISSUE THREAD

**Issue by midu** [blueapron/eventosaurus#21]
_Keeping track some of the feedback I've heard since we made the gem public, not meant to be super high priority._

Quoting a fellow engineer:

> Funny to imagine a bunch of random people's code with `Blueapron::Events` in it though heh

**Comment by keithmgould** [comment]
Agreed I'm hearing the same thing.

**Comment by keithmgould** [comment]
Event's new name is: Eventosaurus

**Comment by midu** [comment]
is that a food?

**Comment by keithmgould** [comment]
non

**Comment by midu** [comment]
🍔
