### ISSUE TITLE
Introduce a testing mode

### ISSUE THREAD

**Issue by HoffsMH** [blueapron/eventosaurus#30]
`test-mode` might be something that could be enabled in config and used in a spec helper in a rails project to make testing with the gem easier and require less stubbing.

**Comment by keithmgould** [comment]
I think the simplest thing for the user is to add a line in rails_helper.rb (or equivalent) as follows:

```
Eventosaurus.enable_test_mode
```

This would stub the basic #store method, returning `true`

As far as writing, we can stub the #run method (the method which is called at the end of a query), returning `nil`.

**Comment by HoffsMH** [comment]
Merged, closing this.
